replicaCount: 2

image:
  repository: ghcr.io/rso-2024-group-12/microservice-narocila
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8083

nameOverride: ""
fullnameOverride: ""
